version: "3.9"

services:

  # http://localhost:8080/
  # spark://localhost:7077
  spark_master:
    ports:
      - '8080:8080' # web-ui
      - '7077:7077' # executor
    hostname: spark-master-host
    build:
      context: .
      dockerfile: .docker-compose/spark/Dockerfile
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    healthcheck:
      test: curl --fail http://localhost:8080/ || exit 1
      start_period: 10s
      interval: 5s
      retries: 5
      timeout: 3s

  spark_worker_1:
    build:
      context: .
      dockerfile: .docker-compose/spark/Dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master-host:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    healthcheck:
      test: curl --fail http://localhost:8081/ || exit 1
      start_period: 10s
      interval: 5s
      retries: 5
      timeout: 3s
    depends_on:
      spark_master:
        condition: service_healthy

  spark_worker_2:
    build:
      context: .
      dockerfile: .docker-compose/spark/Dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master-host:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    healthcheck:
      test: curl --fail http://localhost:8081/ || exit 1
      start_period: 10s
      interval: 5s
      retries: 5
      timeout: 3s
    depends_on:
      spark_master:
        condition: service_healthy